merge_queue:
  max_parallel_checks: 4
merge_protections_settings:
  auto_merge_conditions: true
queue_rules:
  - name: Auto Queue
    queue_conditions:
      - base = main
    merge_conditions:
      - base = main
      - check-success = @github-actions/fast-gates
      - check-success = @github-actions/build-and-test
    branch_protection_injection_mode: none
merge_protections:
  - name: Auto Merge
    if:
      - base = main
    success_conditions:
      - check-success = @github-actions/fast-gates
